export const MAP_DATA = {
  // worldMaxWidth: 0,
  // worldMaxHeight: 0,
  spaceSize: 256,
  outsideSize: 256,

  // gridBorder: 0,
  cellSize: 32,
  minCol: 20,
  maxCol: 60,
  minRow: 20,
  maxRow: 60,

  basePopulation:20,
  upgradePopulation: 5,
  waveCount: 6,
  minRocks: 0.10,
  maxRocks: 0.33,
  minAreaRadius: 64,
  maxAreaRadius: 192,
  minAreaMultiplier: 1.1,
  maxAreaMultiplier: 2,

  baseLife: 100,
  baseGold: 20000,
  baseIncome: 10,
  // baseSmallWall: 20,
  // baseBigWall: 20,
  wallPrice: 20,
  baseTowerUpgrade: 2,
  // baseIncomeUpgrade: 20,
  // baseDestroyUpgrade: 20,

  minPriceMultiplier: 1,
  maxPriceMultiplier: 10,
  minUpgradeMultiplier: 0.2,
  maxUpgradeMultiplier: 2,
};