export const TOWERS_DATA = [
  {
    id: "basic",
    type: "tower",
    name: "Basic Tower",
    description: "Une tour qui pue.",
    damage: 10,
    attackSpeed: 10,
    range: 20,
    splash: 1,
    projectile: 1,
    area: false,
    pierce: false,
    pierceCount: 0,
    bounce: false,
    bounceCount: 0,
    cone: 360,
    price: 20,
  },
  {
    id: "flame_thrower",
    type: "tower",
    name: "Flame Thrower",
    description: "Une tour qui jète du feu follet.",
    damage: 5,
    attackSpeed: 15,
    range: 10,
    splash: 1,
    projectile: 1,
    area: true,
    pierce: false,
    pierceCount: 0,
    bounce: false,
    bounceCount: 0,
    cone: 90,
    price: 40,
  },
  {
    id: "electric_tower",
    type: "tower",
    name: "Electric Tower",
    description: "Une tour qui zappy zap.",
    damage: 8,
    attackSpeed: 25,
    range: 15,
    splash: 1,
    projectile: 1,
    area: true,
    pierce: false,
    pierceCount: 0,
    bounce: true,
    bounceCount: 3,
    cone: 360,
    price: 40,
  },
];