export const MAP_DATA = {
  // worldMaxWidth: 0,
  // worldMaxHeight: 0,
  spaceSize: 256,
  outsideSize: 256,

  // gridBorder: 0,
  cellSize: 32,
  minCol: 20,
  maxCol: 60,
  minRow: 20,
  maxRow: 60,

  baseMaxPopulation:20,
  upgradePopulation: 5,
  waveCount: 6,
  waveTimer: 30,
  minRocks: 10,
  maxRocks: 33,

  minAreaRadius: 64,
  maxAreaRadius: 192,
  // negativeAreaMultiplier: 50,
  minAreaMultiplier: 10,
  maxAreaMultiplier: 90,
  areaTypes: ['damage', 'attackSpeed', 'range', 'speed'],

  baseLives: 100,
  baseGold: 20000,
  baseIncome: 10,
  // baseSmallWall: 20,
  // baseBigWall: 20,
  wallPrice: 20,
  baseTowerUpgrade: 2,
  // baseIncomeUpgrade: 20,
  // baseDestroyUpgrade: 20,

  minPriceMultiplier: 100,
  maxPriceMultiplier: 1000,
  minUpgradeMultiplier: 110,
  maxUpgradeMultiplier: 200,
};